* Print Your GPG Fingerprint

Print your GPG key fingerprint with LaTeX, and be better prepared for
[[http://keysigning.org/methods/adhoc][ad hoc signings]] at the next
[[https://en.wikipedia.org/wiki/Key_signing_party][key signing party]]!

First, download the LaTeX code which is public domain:
[[file:fingerprint.tex][fingerprint.tex]]

Then, adjust the key ID so it will print your own key rather than mine.
Also adjust the number of repetitions to fill the page:
: % Key ID to print
: \newcommand{\keyid}{<b>5F8990AF</b>}
: 
: % Number of repetitions
: \newcommand{\repetitions}{<b>8</b>}

Finally, generate the PDF file:
: sh fingerprint.tex

The [[#result][result]] is shown below. Have fun!

** [related]: Related Projects

- ~gpg-key2ps~ from the [[https://packages.debian.org/sid/signing-party][signing-party]]

** [internals]: Internals

The short command ~sh fingerprint.tex~ works because the LaTeX code is
written in a special way, so
[[http://www.profv.de/literate-programming/][it is also a working shell script]]
which executes ~pdflatex~ and removes all temporary files.
Of course, you can also call ~pdflatex~ by hand. In that case, don't
forget to provide the ~--shell-escape~ option, otherwise the LaTeX file
isn't allowed to run ~GPG~ to retrieve your key fingerprint:
: pdflatex --shell-escape fingerprint.tex

** [result]: Result

[[file:example.pdf][file:example.png]]

(In case you want to know, the preview image was generated with
[[http://www.graphicsmagick.org/][GraphicsMagick]]:
~gm convert -density 60 example.pdf example.png~)

See [[https://vog.github.io/fingerprint/][project homepage]] for more details.
